### ISSUE TITLE
Class 'Jhoule\Mailshake\MailshakeRequest' not found

### ISSUE THREAD

**Issue by frankcrissalem** [jasonhoule/laravel-mailshake#1]
Good day!

I have followed the installation but got an error saying: 
`exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
file: "C:\xampp\htdocs\my-tool\vendor\jhoule\mailshake\src\Me.php"
line: 8
message: "Class 'Jhoule\Mailshake\MailshakeRequest' not found"`

I've been calling the class from my controller
`
    	$mailshake_me = new Me();
    	return $mailshake_me->get();
`

Thanks in advance!

**Comment by jasonhoule** [comment]
Hello @frankcrissalem! I apologize for the delayed response. It appears that I missed updating this class after I did some refactoring. I will provide a fix shortly.
