### ISSUE TITLE
Activity::replies undefined property exception

### ISSUE THREAD

**Issue by rokaslit6** [jasonhoule/laravel-mailshake#4]
Hi,

Thanks for keeping this wrapper updated!

I've been fiddling around with it & was trying to setup the Activity::replies request, but I kept running into this error:

![Screen Shot 2020-01-22 at 2 45 16 PM](https://user-images.githubusercontent.com/30793715/72895465-18a8f900-3d26-11ea-868c-c999d0c9c029.png)

And this is how my request looks like:
`$items = Activity::replies(null, null, null, null, 10)->flatten()->slice(1);
        dd($items);`

I suspect this error pops up because some replies (bounces, unsubscribes or just replies) return a response without the "parent" object in the collection, but I'm not sure yet.

My suspicion came from the fact that I don't always get this error, even though I don't change anything in my code. So, the response from Mailshake probably contains some stuff that the request can't handle yet.

Any thoughts on this?

@jasonhoule

**Comment by jasonhoule** [comment]
I believe you are correct. The Mailshake API does not seem to be very consistent with their responses. I'll dig into this further.

**Comment by rokaslit6** [comment]
Totally agreed. I had them fix a leftover TODO for pushes about a year ago.

**Comment by jasonhoule** [comment]
@rokaslit6 I was finally able to get to this and it should be fixed now if you would like to test it out. I tried to test it but I cannot find a reply that does not have a parent. I tested it from tinker and it worked as expected. I hope to get to writing tests for this sometime soon.

https://github.com/jasonhoule/laravel-mailshake/blob/0807e9e5c71188d703482c158e9262ba762444ed/src/Requests/Activity/Replies.php#L68

**Comment by rokaslit6** [comment]
@jasonhoule thanks, you're a savior!

I will test this out throughout the day & let you know if I find anything again. I will also let you know if I don't find anything.

Give me like 5 hrs or so.

**Comment by rokaslit6** [comment]
@jasonhoule update.
I've been fiddling around & it seemed to be working fine throughout the day, but I randomly got this exception:
`Return value of Jhoule\Mailshake\Requests\Activity\Replies::getSentMessage() must be an instance of Jhoule\Mailshake\Models\SentMessage, null returned`

![Screen Shot 2020-01-28 at 3 06 26 PM](https://user-images.githubusercontent.com/30793715/73266901-8c447d80-41e0-11ea-832f-67e2c7b0ccee.png)

**Comment by jasonhoule** [comment]
Good catch. Thank you! It now will return an empty instance of [SentMessage](https://github.com/jasonhoule/laravel-mailshake/blob/master/src/Models/SentMessage.php) instead of null.

**Comment by rokaslit6** [comment]
Thanks! I will be using your wrapper long-term & I will post any further issues if there will be any. Having said that, I will close this issue as resolved.

**Comment by rokaslit6** [comment]
FYI Just wanted to let you know - if the reply type is "**out-of-office**", then the whole "**parent**" object is returned as null., but it should still return some data as the Mailshake docs tells us.
Here's what they say in the docs:
![Screen Shot 2020-01-29 at 12 05 32 PM](https://user-images.githubusercontent.com/30793715/73347088-ac7f4580-428f-11ea-8c7f-0520f011c430.png)

And here's what it looks like when it happens:
![Screen Shot 2020-01-29 at 11 57 25 AM](https://user-images.githubusercontent.com/30793715/73347113-b99c3480-428f-11ea-906d-c067db723685.png)

I got around this easily with:
`if ($item->type != 'out-of-office')`

@jasonhoule

**Comment by jasonhoule** [comment]
@rokaslit6 That is interesting. Thank you for mentioning this. I'll try to figure out what is happening there.
